# Generated by Django 5.2.8 on 2025-11-07 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Pagamento')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='URL do Pagamento')),
                ('tipo_doacao', models.CharField(blank=True, choices=[('brinquedos', 'Brinquedos'), ('alimentacao', 'Alimentação')], max_length=20, null=True, verbose_name='Tipo de Doação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('nome_doador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Doador')),
                ('email_doador', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Doador')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data'],
            },
        ),
    ]
