# Generated by Django 5.2.8 on 2025-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code PIX (texto)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code PIX (Base64)'),
        ),
    ]
